cities_dict = {"москва": "moscow", "санкт-петербург": "saint-petersburg", "абакан": "abakan", "абдулино": "abdulino",
               "абинск": "abinsk", "агидель": "agidel",
               "агрыз": "agryz", "азнакаево": "aznakaevo", "азов": "azov", "аксай": "aksay", "актау": "aktau",
               "актобе": "aktobe", "алапаевск": "alapaevsk", "алатырь": "alatyr", "алдан": "aldan", "алейск": "aleysk",
               "александров": "aleksandrov", "алеsaint-petersburgксандровка": "aleksandrovka",
               "александровск": "aleksandrovsk",
               "алексеевка": "alekseevka", "алексин": "aleksin", "алматы": "almaty", "алушта": "alushta",
               "альметьевск": "almetyevsk", "анадырь": "anadyr", "анапа": "anapa", "ангарск": "angarsk",
               "анжеро-судженск": "angero-sudgensk", "апатиты": "apatity", "апшеронск": "apsheronsk",
               "ардатов": "ardatov", "арзамас": "arzamas", "армавир": "armavir", "арсеньев": "arsenev",
               "арсеньево": "arsenjevo", "артём": "artem", "архангельск": "arhangelsk",
               "архангельское": "arkhangelskoe", "асбест": "asbest", "аскарово": "askarovo", "аскино": "askino",
               "астрахань": "astrahan", "атырау": "atyrau", "атяшево": "atyashevo", "ахтубинск": "ahtubinsk",
               "ачинск": "achinsk", "аша": "asha", "баймак": "baimak", "бакалы": "bakali", "балаково": "balakovo",
               "балахна": "balakhna", "балашов": "balashev", "барановичи": "baranavichy", "барнаул": "barnaul",
               "бачатский": "bachatsky", "белая глина": "belaya-glina", "белая калитва": "belaya-kalitva",
               "белгород": "belgorod", "белебей": "belebey", "белово": "belovo", "белогорск": "belogorsk",
               "белорецк": "beloretsk", "белореченск": "belorechensk", "белоярский": "beloyarskiy", "белёв": "belyov",
               "березники": "berezniki", "бижбуляк": "bizhbulyak", "бийск": "biysk", "бикин": "bikin",
               "биробиджан": "birobidgan", "бирск": "birsk", "благовещенск (башкортостан)": "blagoveschensk",
               "благовещенск (амурская область)": "blagoveshchensk", "бобруйск": "bobruisk",
               "богданович": "bogdanovich", "богородицк": "bogoroditsk", "борисоглебск": "borisoglebsk",
               "боровичи": "borovichy", "братск": "bratsk", "брест": "brest", "брянск": "bryansk",
               "бугульма": "bugulma", "бугуруслан": "buguruslan", "будённовск": "budennovsk", "бузулук": "buzuluk",
               "буланаш": "bulanash", "бураево": "buraevo", "бутурлиновка": "buturlinovka", "валдай": "valday",
               "валуйки": "valuyki", "ванино": "vanino", "великие луки": "velikie-luky",
               "великий новгород": "veliky-novgorod", "вельск": "velsk", "венёв": "venev",
               "верхнеяркеево": "verkhneyarkeevo", "верхние татышлы": "verkhnie-tatishli",
               "верхняя салда": "verhnya-salda", "визинга": "vizinga", "витебск": "vitebsk",
               "владивосток": "vladivostok", "владикавказ": "vladikavkaz", "владимир": "vladimir",
               "волгоград": "volgograd", "волгодонск": "volgodonsk", "волжск": "volzhsk", "вологда": "vologda",
               "волоколамск": "volokolamsk", "волхов": "volhov", "волчанск": "volchansk", "вольск": "volsk",
               "воркута": "vorkuta", "воронеж": "voronezh", "воскресенск": "voskresensk", "воткинск": "votkinsk",
               "выборг": "vyborg", "выкса": "vyksa", "вышний волочёк": "vishniy-volochek", "вяземский": "vyazemsky",
               "вязники": "vyazniki", "вязьма": "vyazma", "вятские поляны": "vyatskie-polyani", "газ-сале": "gaz-sale",
               "галич": "galich", "гатчина": "gatchina", "геленджик": "gelendgik", "глазов": "glazov",
               "глушково": "glushkovo", "голышманово": "golishmanovo", "гомель": "gomel", "горки ": "gorki",
               "горно-алтайск": "gorno-altaysk", "горнозаводск": "gornozavodsk", "горняк": "gornyak",
               "городец": "gorodets", "городок": "gorodok", "гороховец": "gorohovec", "грайворон": "grayvoron",
               "грамотеино": "gramoteino", "гродно": "grodno", "грозный": "grozniy", "грязи": "gryazi",
               "губаха": "gubakha", "губкин": "gubkin", "губкинский": "gubkinskiy", "гудермес": "gudermes",
               "гуково": "gukovo", "гулькевичи": "gulkevichi", "гурьевск\n": "gurevsk", "гусев": "gusev",
               "гусь-хрустальный": "gus-chrustalniy", "дальнереченск": "dalnerechensk", "данилов": "danilov",
               "джалиль": "dzhalil", "джанкой": "jankoy", "дивное": "divnoe", "димитровград": "dimitrovgrad",
               "дмитров": "dmitrov", "донецк": "donetsk-rnd", "дубна": "dubna100803", "дудинка": "dudinka",
               "дюртюли": "dyurtyuli", "евпатория": "evpatoria", "егорьевск": "egorievsk", "ейск": "yesk",
               "екатеринбург": "yekaterinburg", "елабуга": "elabuga", "елец": "yelets", "елизово": "elizovo",
               "емва": "emva", "ермолаево": "ermolaevo", "ефремов": "efremov", "жанаозен": "zhanaozen",
               "железногорск": "zheleznogorsk", "железногорск-илимский": "zheleznogorsk-ilimsky",
               "жигулёвск": "zhiguliovsk", "жирновск": "zhirnovsk", "житикара": "zhitikara", "житковичи": "zhytkovichy",
               "жлобин": "zhlobin", "жуковка": "zhukovka", "завьялово": "zavjyalovo", "заинск": "zainsk",
               "зарайск": "zaraysk", "заречный": "zarechny", "заринск": "zarinsk", "зеленогорск": "zelenogorsk",
               "зеленоградск": "zelenogradsk", "зеленодольск": "zelenodolsk", "зерноград": "zernograd",
               "зилаир": "zilair", "златоуст": "zlatoust", "змеиногорск": "zmeinogorsk",
               "зубова поляна": "zubova-poliana", "иваново": "ivanovo", "ивдель": "ivdel", "иглино": "iglino",
               "ижевск": "izhevsk", "ижма": "izhma", "инзер": "inzer", "инсар": "insar", "инта": "inta",
               "ипатово": "ipatovo", "ирбит": "irbit", "иркутск": "irkutsk", "искитим": "iskitim", "истра": "istra",
               "исянгулово": "isyangulovo", "ишим": "ishim", "йошкар-ола": "yoshkar-ola", "казань": "kazan",
               "калач": "kalach", "калининград": "kaliningrad", "калининец": "kalininets", "калинковичи": "kalinovichi",
               "калуга": "kaluga", "камбарка": "kambarka", "каменка": "kamenka",
               "каменск-уральский": "kamensk-uralskiy", "каменск-шахтинский": "kamensk-shakhtinsky",
               "камышин": "kamishin", "камышлов": "kamyshlov", "кандалакша": "kandalaksha", "канск": "kansk",
               "караганда": "karaganda", "караидель": "karaidel", "кармаскалы": "karmaskaly", "касимов": "kasimov",
               "катав-ивановск": "katav-ivanovsk", "качканар": "kachkanar", "кашира": "kashira", "кемерово": "kemerovo",
               "керчь": "kerch", "кизляр": "kizlyar", "кимовск": "kimovsk", "кимры": "kimry", "кингисепп": "kingisepp",
               "кинель": "kinel", "кинешма": "kineshma", "киргиз-мияки": "kirgiz-miyaki", "киреевск": "kireevsk",
               "киржач": "kirzach", "кириши": "kirishi", "киров": "kirov", "кировград": "kirovgrad",
               "киселёвск": "kiselevsk", "кисловодск": "kislovodsk", "климово": "klimovo", "клин": "klin",
               "клинцы": "klintsy", "ковдор": "kovdor", "ковров": "kovrov", "ковылкино": "kovylkino",
               "когалым": "kogalym", "козельск": "kozelsk", "козьмодемьянск": "kozmodemyansk", "коломна": "kolomna",
               "колпашево": "kolpashevo", "кольчугино": "kolchugino", "комсомольск-на-амуре": "komsomolsk_na_amure",
               "конаково": "konakovo", "кондопога": "kondopoga", "кондрово": "kondrovo",
               "константиновск": "konstantinovsk", "коряжма": "koryagma", "костанай": "kostanai",
               "кострома": "kostroma", "котлас": "kotlas", "кохма": "kohma", "краснобродский": "krasnobrodsky",
               "красногвардейское": "krasnogvardejskoye", "краснодар": "krasnodar",
               "красноперекопск": "krasnoperekopsk", "красноселькуп": "krasnoselkup",
               "краснослободск": "krasnoslobodsk", "краснотурьинск": "krasnorurinsk", "красноуфимск": "krasnoufimsk",
               "красноярск": "krasnoyarsk", "кропоткин": "kropotkin", "крымск": "krymsk", "кубинка": "kubinka",
               "кудымкар": "kudimkar", "кузнецк": "kuznetsk", "куйбышев": "kuybyshev", "кукмор": "kukmor",
               "кулебаки": "kulebaki", "кулунда": "kulunda", "кумертау": "kumertau", "кунгур": "kungur",
               "курган": "kurgan", "курганинск": "kurganinsk", "куркино": "kurkino", "куровское": "kurovskoye",
               "курск": "kursk", "курчатов": "kurchatov", "куса": "kusa", "кушва": "kushva",
               "кушнаренково": "kushnarenkovo", "кызыл": "kyzyl", "кызылорда": "kyzylorda", "кыштым": "kyshtym",
               "лабинск": "labinsk", "лабытнанги": "labytnangi", "лангепас": "langepas", "ленино": "lenino",
               "лениногорск": "leninigorsk", "ленинск": "leninsk", "ленинск-кузнецкий": "leninsk-kuznetskiy",
               "ленск": "lensk", "лесной": "lesnoy", "лесосибирск": "lesosibirsk", "ливны": "livny",
               "липецк": "lipetsk", "лиски": "lisky", "лодейное поле": "lodeynoe-pole", "лучегорск": "luchegorsk",
               "лысково": "lyskovo", "лысьва": "lysva", "льгов": "lgov", "людиново": "ljudinovo", "лямбирь": "lyambir",
               "лянтор": "lyantor", "магадан": "magadan", "магнитогорск": "magnitogorsk", "майкоп": "maykop",
               "малая пурга": "malaya-purga", "малоярославец": "maloyaroslavets", "мамадыш": "mamadysh",
               "мантурово": "manturovo", "мариинский посад": "mariinskiy-posad", "маркс": "marks",
               "маслянино": "maslyanino", "махачкала": "makhachkala", "мегион": "megion", "медногорск": "mednogorsk",
               "междуреченск": "mezgdurechensk", "мелеуз": "meleuz", "месягутово": "mesyagutovo", "миасс": "miass",
               "миллерово": "millerovo", "минск": "minsk", "минусинск": "minusinsk", "мирный": "mirny",
               "михайловка": "mihaylovka", "михайловское": "mikhaylovskoe", "мичуринск": "michurinsk",
               "могилёв": "mogilev", "можайск": "mozhaysk", "можга": "mozhga", "моздок": "mozdok", "мозырь": "mozyr",
               "мокроус": "mokrous", "мончегорск": "monchegorsk", "морозовск": "morozovsk", "мосальск": "mosalsk",
               "мостовской": "mostovskoi", "мраково": "mrakovo", "муравленко": "myravlenko", "мурманск": "murmansk",
               "муром": "murom", "мценск": "mtsensk", "мыски": "myski", "мышкин": "myshkin",
               "набережные челны": "naberezhnie-chelny", "надым": "nadym", "назарово": "nazarovo", "назрань": "nazran",
               "называевск": "nazyvaevsk", "нальчик": "nalchik", "наро-фоминск": "naro-fominsk",
               "нарьян-мар": "naryan-mar", "находка": "nahodka", "невельск": "nevelsk", "невинномысск": "nevinnomissk",
               "нелидово": "nelidovo", "неман": "neman", "нерехта": "nerekhta", "нефтекамск": "nephtekamsk",
               "нефтекумск": "neftekumsk", "нефтеюганск": "nefteugansk", "нея": "neya",
               "нижневартовск": "nizhnevartovsk", "нижнекамск": "nizhnekamsk", "нижнеудинск": "nizhneudinsk",
               "нижний куранах": "nizhny-kuranakh", "нижний ломов": "nizhny-lomov",
               "нижний новгород": "nizhny-novgorod", "нижний тагил": "nizhniy-tagil", "нижняя салда": "nizhnyaya-salda",
               "нижняя тура": "nignaya-tura", "николаевск-на-амуре": "nikolaevsk-na-amure",
               "новая брянь": "novaya-bryan", "новая игирма": "novaya-igirma", "новая ляля": "novaya-lyalya",
               "новобелокатай": "novobelokatay", "нововоронеж": "novovoronezh", "новодвинск": "novodvinsk",
               "новозыбков": "novozibkov", "новокузнецк": "novokuznetsk", "новомосковск": "novomoskovsk",
               "новороссийск": "novorossiysk", "новосергиевка": "novosergievka", "новосибирск": "novosibirsk",
               "новоуральск": "novouralsk", "новочеркасск": "novocherkassk", "новый уренгой": "noviy-urengoy",
               "ногинск": "noginsk", "нолинск": "nolinsk", "норильск": "norilsk", "ноябрьск": "noyabrsk",
               "нур-султан (астана)": "nur-sultan", "нурлат": "nurlat", "нягань": "nyagan",
               "нязепетровск": "nyazepetrovsk", "няндома": "nyandoma", "обнинск": "obninsk", "общий": "online",
               "объячево": "obyachevo", "одоев": "odoev", "озёрск": "ozersk", "озёры": "ozery",
               "октябрьский": "oktyabrsky", "омск": "omsk", "омутнинск": "omutninsk", "оренбург": "orenburg",
               "орехово-зуево": "orehovo-zuevo", "орск": "orsk", "орша": "orsha", "орёл": "orel", "оса": "osa",
               "осиповичи": "asipovichy", "осташков": "ostashkov", "павлово": "pavlovo", "павловская": "pavlovskaya",
               "павловский посад": "pavlovskiy-posad", "павлодар": "pavlodar", "партизанск": "partizansk",
               "пенза": "penza", "первомайск": "pervomajsk", "первомайское": "pervomajskoye",
               "первоуральск": "pervouralsk", "пермь": "perm", "петриков": "petrikov", "петровск": "petrovsk",
               "петрозаводск": "petrozavodsk", "петропавловск": "petropavlovsk",
               "петропавловск-камчатский": "petropavlovsk-kamchatsky", "печора": "pechora", "пионерский": "pionersky",
               "плавск": "plavsk", "покров": "pokrov", "покровск": "pokrovsk", "покровское": "pokrovskoe",
               "полевской": "polevskoj", "полоцк": "polotsk", "полтавская": "poltavskaya",
               "полярные зори": "polyarnie-zori", "поронайск": "poronaysk", "почеп": "pochep",
               "приморско-ахтарск": "primorsko-ahtarsk", "прокопьевск": "prokopevsk", "прохладный": "prohladny",
               "прохоровка": "prohorovka", "псков": "pskov", "пугачев": "pugachev", "пыть-ях": "pyt-yah",
               "пятигорск": "pyatigorsk", "радужный": "radugniy", "раменское": "ramenskoe", "ревда": "revda",
               "республика саха (якутия)": "sakha-(yakutia)-republic", "рефтинский": "reftinsky", "речица": "rechitsa",
               "ржев": "rzhev", "рогачёв": "rogachev", "рославль": "roslavl", "россошь": "rossosh", "ростов": "rostov",
               "ростов-на-дону": "rostov-na-donu", "рошаль": "roshal", "ртищево": "rtischevo", "рубцовск": "rubtsovsk",
               "рудня": "rudnya", "руза": "ruza", "рузаевка": "ruzaevka", "рыбинск": "rybinsk", "рыльск": "rilsk",
               "рязань": "ryazan", "саки": "saky", "салават": "salavat", "салехард": "salekhard", "сальск": "salsk",
               "самара": "samara", "саранск": "saransk", "саратов": "saratov", "саров": "sarov", "сасово": "sasovo",
               "сатка": "satka", "сафоново": "safonovo", "саянск": "sayansk", "свободный": "svobodniy",
               "севастополь": "sevastopol", "северобайкальск": "severobaykalsk", "северодвинск": "severodvinsk",
               "североморск": "severomorsk", "североуральск": "severouralsk", "сегежа": "segezha", "семей": "semey",
               "семикаракорск": "semikarakorsk", "сенгилей": "sengiley", "серафимович": "serafimovich",
               "серафимовский": "serafimovsky", "сергач": "sergach", "сергиев посад": "sergiev-posad",
               "сердобск": "serdobsk", "серов": "serov", "серпухов": "serpuhov", "сим": "sim",
               "симферополь": "simferopol", "скопин": "skopin", "славгород": "slavgorod",
               "славянск-на-кубани": "slavyansk-na-kubani", "смоленск": "smolensk", "снежинск": "sneginsk",
               "советск": "sovetsk", "советская гавань": "sovetskaya-gavan", "советский": "sovetsky", "сокол": "sokol",
               "соликамск": "solikamsk", "солнечногорск": "solnechnogorsk", "сосенский": "sosensky",
               "сосново-озёрское": "sosnovo-ozerskoe", "сосновый бор": "sosnoviy-bor", "сочи": "sochi",
               "спасск-дальний": "spassk-dalniy", "ставрополь": "stavropol", "старая русса": "staraya-russa",
               "старобалтачево": "starobaltachevo", "старое шайгово": "staroe-shaygovo",
               "староминская": "starominskaya", "старощербиновская": "starosherbinovskaya",
               "старый оскол": "stariy-oskol", "стерлибашево": "sterlibashevo", "стерлитамак": "sterlitamak",
               "стрежевой": "strezgevoy", "ступино": "stupino", "субханкулово": "subkhankulovo", "суворов": "suvorov",
               "судак": "sudak", "суджа": "sudzha", "суздаль": "suzdal", "сургут": "surgut", "суровикино": "surovikino",
               "сухиничи": "suhinichi", "сухой лог": "sukhoi-log", "сызрань": "sizran", "сыктывкар": "syktyvkar",
               "тавда": "tavda", "таганрог": "taganrog", "тазовский": "tazovsky", "тайшет": "tayshet",
               "тамбов": "tambov", "тараз": "taraz", "тарко-сале": "tarko-sale", "таруса": "tarusa",
               "татарск": "tatarsk", "таштагол": "tashtagol", "тбилисская": "tbilisskaya", "тверь": "tver",
               "темрюк": "temryuk", "тимашевск": "timashovsk", "тихвин": "tikhvin", "тихорецк": "tikhoretsk",
               "тобольск": "tobolsk", "тольятти": "togliatti", "томск": "tomsk", "топки": "topki",
               "торбеево": "torbeevo", "торопец": "toropets", "троицк": "troitsk", "трубчевск": "trubchevsk",
               "трёхгорный": "trehgorniy", "туапсе": "tuapse", "тугулым": "tugulim", "тула": "tula", "тулун": "tulun",
               "туркестан": "turkestan", "туртас": "turtas", "тюмень": "tyumen", "углич": "uglich", "удомля": "udomlya",
               "узловая": "uzlovaya", "улан-удэ": "ulan-ude", "ульяновск": "ulyanovsk", "унеча": "unecha",
               "урай": "uray", "уральск": "uralsk", "урень": "uren", "урюпинск": "uryupinsk", "усинск": "usinsk",
               "усмань": "usman", "усолье-сибирское": "usole-sibirskoe", "уссурийск": "ussuriysk",
               "усть-илимск": "ust-ilimsk", "усть-каменогорск": "ust-kamenogorsk", "усть-катав": "ust-katav",
               "усть-кулом": "ust-kulom", "усть-кут": "ust-kut", "уфа": "ufa", "ухта": "uhta", "учалы": "uchaly",
               "феодосия": "feodosia", "фролово": "phrolovo", "хабаровск": "khabarovsk",
               "ханты-мансийск": "khanty-mansiysk", "холмск": "holmsk", "чайковский": "chaikovsky",
               "чебаркуль": "chebarkul", "чебоксары": "cheboksary", "чекмагуш": "chekmagush",
               "челябинск": "chelyabinsk", "чердаклы": "cherdakli", "череповец": "cherepovets", "черкесск": "cherkessk",
               "черниговка": "chernigovka", "черноголовка": "chernogolovka", "черноморское": "chernomorskoe",
               "чернушка": "chernushka", "чернь": "chern", "черняховск": "chernyahovsk", "чехов": "chehov",
               "чистополь": "chistopol", "чита": "chita", "чишмы": "chishmy", "чудово": "chudovo",
               "чусовой": "chusovoy", "шадринск": "shadrinsk", "шаран": "sharan", "шарыпово": "sharypovo",
               "шарья": "sharya", "шатура": "shatura", "шахты": "shakhty", "шахунья": "shahuniya",
               "шебекино": "shebekino", "шимановск": "shimanovsk", "шумерля": "shumerlya", "шумиха": "shumiha",
               "шуя": "shuya", "шымкент": "chimkent", "электрогорск": "elektrogorsk", "электросталь": "elektrostal",
               "элиста": "elista", "энем": "enem", "югорск": "ugorsk", "южно-сахалинск": "sakhalinsk",
               "южноуральск": "ugnouralsk", "юрга": "urga", "якутск": "yakutsk", "ялта": "yalta",
               "ялуторовск": "yalutorovsk", "янаул": "yanaul", "яр": "yar", "ярославль": "yaroslavl",
               "ярцево": "yartsevo", "ясногорск": "yasnogorsk", "яшкино": "yashkino"}
